#!/bin/bash

echo "🚀 Combined Deployment Script for Food Blog"
echo "============================================="
echo ""

echo "📋 Prerequisites:"
echo "✅ GitHub repository connected to Render"
echo "✅ MongoDB database set up"
echo "✅ Cloudinary account configured"
echo ""

echo "🔧 Step 1: Create Web Service on Render"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect your GitHub repository: Ahmedtarekmekled/Amjadzetouneh"
echo ""

echo "⚙️ Step 2: Configure Service Settings"
echo "Basic Settings:"
echo "  - Name: amjadzetouneh"
echo "  - Environment: Node"
echo "  - Region: Choose closest to your users"
echo "  - Branch: main"
echo "  - Root Directory: Leave empty (root of repo)"
echo "  - Build Command: npm run install:all && npm run build"
echo "  - Start Command: npm start"
echo ""

echo "🔑 Step 3: Add Environment Variables"
echo "Click 'Environment' tab and add these variables:"
echo ""
echo "   MONGODB_URI=your_mongodb_connection_string"
echo "   JWT_SECRET=your_jwt_secret_key"
echo "   CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name"
echo "   CLOUDINARY_API_KEY=your_cloudinary_api_key"
echo "   CLOUDINARY_API_SECRET=your_cloudinary_api_secret"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   NEXT_PUBLIC_API_URL=https://amjadzetouneh.onrender.com/api"
echo ""

echo "4. 🎉 Deploy and Test:"
echo "   - Click 'Create Web Service'"
echo "   - Wait for deployment"
echo "   - Test: https://amjadzetouneh.onrender.com"
echo ""

echo "📖 For detailed instructions, see: render-combined-deploy.md"
echo ""

echo "🎉 Your food blog will be live at: https://amjadzetouneh.onrender.com"
echo "🔗 Your API will be at: https://amjadzetouneh.onrender.com/api" 